baseURL = "https://florianeinfalt.de"
languageCode = "en-gb"
title = "Florian Einfalt – Developer"
theme = "hucore"

copyright = "&copy; 2018-2020 Florian Einfalt"

[taxonomies]
tag = "tags"
category = "categories"

[params]
description = "A personal blog, mostly about Python development"
keywords = ["development", "python"]
author = "Florian Einfalt"
sharingicons = false

[params.highlight]
style = "github"
languages = ["python3"]

[[params.social]]
url = "https://github.com/florianeinfalt"
fa_icon = "fa-github"

[[params.social]]
url = "https://linkedin.com/in/florianeinfalt"
fa_icon = "fa-linkedin-square"

[[params.social]]
url = "/index.xml"
fa_icon = "fa-rss"
